#!/bin/bash

#Find our distribution
FULLPATH=`readlink -f $0`
TOP=`dirname $FULLPATH`
TOP=`dirname $TOP`

#Do xauth list | grep unix:0
#inside docker shell xauth add :0 MIT-MAGIC... digest..

#user should be a member of video and render to get full access to gpu


#IMAGE=ads-rh8:latest
IMAGE=freecad-build:latest

GIDS=( $(id -G) )  #All of my groups
unset GIDS[0]      #remove primary group
for g in "${GIDS[@]}"
do
    G+=" --group-add=$g"
done

#export BASH_ENV=$TOP/ADSDocker/env

#RM=""
RM=" --rm "

#U=""
U=" --user $(id -u):$(id -g) $G"

VOLS=' --volume=/etc/group:/etc/group:ro '
VOLS+='--volume=/etc/localtime:/etc/localtime:ro '
VOLS+='--volume=/etc/passwd:/etc/passwd:ro '
VOLS+='--volume=/etc/shadow:/etc/shadow:ro '
VOLS+='--volume=/etc/sudoers.d:/etc/sudoers.d:ro '
VOLS+='--volume=/tmp/.X11-unix:/tmp/.X11-unix:rw '
VOLS+="--volume=/home/${USER}:/home/${USER} "
VOLS+='--volume=/opt:/opt '
VOLS+="--device=/dev/dri "
VOLS+="--device=/dev/vga_arbiter "
VOLS+="--volume=/projects:/projects "


NVS=( $(ls /dev/nvidia* 2>/dev/null) )
for N in "${NVS[@]}"
do
   VOLS+="--device=$N "
done

SEC=''

NET='--network=host '

export PATH=$PATH:/opt/ADS/ADSDocker
docker run $RM -it $U --env="DISPLAY" $VOLS --ipc="host" $NET \
       $SEC \
       -w="/home/${USER}" \
       --hostname="mrflt-fcd" \
       --name="freecadbuild" \
       ${IMAGE} /bin/bash 


