#!/bin/bash
#
#cmake -DBUILD_FEM_NETGEN=1 -DFREECAD_USE_EXTERNAL_PIVY=1 -DCMAKE_BUILD_TYPE=Release -DBoost_INCLUDE_DIRS=/usr/include/boost ..

#COMPILER=" -DCMAKE_CXX_COMPILER=/usr/bin/g++-10 -DCMAKE_C_COMPILER=/usr/bin/gcc-10"
COMPILER=""
COMPILER+=" -DCMAKE_VERBOSE_MAKEFILE=ON "
#COMPILER+=" -DCMAKE_CXX_FLAGS=\" -fpermissive -fno-access-control \" "


PYTHON3=" -DBUILD_QT5=ON -DPYTHON_LIBRARY=/usr/lib64/libpython3.7m.so \
    -DPYTHON_INCLUDE_DIR=/usr/include/python3.7m \
    -DPYTHON_PACKAGES_PATH=/usr/lib64/python3.7/site-packages \
    -DPYTHON_EXECUTABLE=/usr/bin/python3.7 "

PYTHON2=" "

PYTHON3A=" -DBUILD_QT5=ON -DPYTHON_EXECUTABLE=/usr/bin/python3 "

PYTHON="${PYTHON3A}"

NETGEN=""
NETGEN=" -DBUILD_FEM_NETGEN=0 -D_OCC64=1 "

set -x

/bin/bash -c "cmake ${COMPILER} ${PYTHON} ${NETGEN} -DFREECAD_USE_EXTERNAL_PIVY=1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/opt/FreeCAD -DBoost_INCLUDE_DIRS=/usr/include/boost .."
